[package]
name = "simplified_ddflow"
version = "0.1.0"
authors = ["David Spies <dnspies@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
differential-dataflow = "0.11.0"
timely = "0.11.1"
